api:
  host: 187.74.10.160
  port: 8083
sql:
  host: 10.58.192.51
  port: 1433
  user: produtostbfg
  password: Luccasantos10@
de para:
  cat pw: depara/cat_pw.json
  cat pg: depara/cat_pg.json
  desc pw: depara/desc_pw.json
  desc pg: depara/desc_pg.json
  color: depara/color.json
  cat smk: depara/cat_smk.json
  desc smk: depara/desc_smk.json
  

  
  
  